# c = continuous
# cat = categorical
# b = boolean
# boost = boostexter feature for labels
# show = this causes display in CompareController#show
# showList = for direct view, this causes display in .itemfeatures

####Spaces are required between elements in an array

camera_bestbuy:
    url: 
        localhost: 12
        bestbuy: 12
        ilovecameras: 12
        ilovecameras.optemo.com: 12
    layout: assist
    specs:
        General:
            price:
                type: Continuous
                used_for: [filter, cluster, show]
                prefdir: -1
                min: 1
                max: 10000
                utility: 5
                cluster: 5
            maxresolution: 
                type: Continuous
                used_for: [desc, filter, cluster, show]
                utility: 5 
                cluster: 5 
            screensize:
                type: Continuous
                used_for: [desc, filter, show]
            opticalzoom:
                type: Continuous
                used_for: [desc, filter, cluster, show]
                utility: 5
                cluster: 5    
            brand:
                type: Categorical
                used_for: [show, filter, cluster]
                utility: 5
                prefered: [Canon, Sony, Nikon] 
            color:
                type: Categorical
                used_for: [show, filter]
            customerRating:
                type: Continuous
                used_for: [show]
        Status:
            onsale:
                type: Binary
                used_for: [filter]
            isClearance:
                type: Binary
                used_for: [filter]
            isOnlineOnly:
                type: Binary
                used_for: [filter]
            toprated:
                type: Binary
                used_for: [filter]
        Video Resolution:
            videoresolution720:
                type: Binary
                used_for: [filter]
            videoresolution1080:
                type: Binary
                used_for: [filter]
        New Technology:
            hdmi:
                type: Binary
                used_for: [filter]
            touchscreen:
                type: Binary
                used_for: [filter]
            imagestabilization:
                type: Binary
                used_for: [filter]
            waterproof:
                type: Binary
                used_for: [show, filter]
            oled:
                type: Binary
                used_for: [filter]
            gps:
                type: Binary
                used_for: [show, filter]
            projector:
                type: Binary
                used_for: [show, filter]
            3d:
                type: Binary
                used_for: [show, filter]
            sweeppanorama:
                type: Binary
                used_for: [show, filter]
            frontlcd:
                type: Binary
                used_for: [show, filter]

# 29171  --  this is a small subset of cameras, with faster scraping & lower load for testing
tv_bestbuy:
    url: 
        besttv: 12
    category_id: [21344]
    layout: assist
    specs:
        General:
            price:
                type: Continuous
                used_for: [filter, cluster, show]
                prefdir: -1
                min: 1
                max: 10000
            maxresolution: 
                type: Continuous
                used_for: [desc, filter, cluster, show]
            screensize:
                type: Continuous
                used_for: [desc, filter, cluster, show]
            power:
                type: Continuous
                used_for: [desc, filter, cluster, show]
            brand:
                type: Categorical
                used_for: [filter, show]
            displaytech:
                type: Categorical
                used_for: [filter, show]